var data = [
  {
    "ValenceChange": 2,
    "ArousalChange": 1,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "15/03/2022 14:17:09",
    "InitStartSong": "Angel's Flight",
    "InitStartSpotifyID": "spotify:track:1tCPxwo9ll7rxCxaEBq06f",
    "InitStartArtist": "Biosphere",
    "InitStartTracktime": 30918,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Tired",
    "InitIntensity": 6,
    "ValenceAim": 1,
    "ArousalAim": 1,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Thinking / problem-solving",
    "InitEnd": "15/03/2022 14:17:11",
    "InitEndSong": "Angel's Flight",
    "InitEndSpotifyID": "spotify:track:1tCPxwo9ll7rxCxaEBq06f",
    "InitEndArtist": "Biosphere",
    "InitEndTracktime": 32516,
    "MainStart": "15/03/2022 14:33:27",
    "MainStartSong": "Dietrofront",
    "MainStartSpotifyID": "spotify:track:0pD3ZURkGEUYtFgB8DIgIk",
    "MainStartArtist": "Matteo Vallicelli",
    "MainStartTracktime": "32,939",
    "MainValence": 1,
    "MainArousal": 3,
    "MainIntensity": 6,
    "MainMusicValence": 1,
    "MainMusicArousal": 3,
    "MusicAttention": 1,
    "Familiar": 1,
    "MainEnjoy": 5,
    "SuitActivity": 3,
    "ReasonMain": "To listen with other people",
    "ReasonMain_label": "WithOthers",
    "Reason": "To express my identity / values",
    "Reason_label": "To express my identity / values",
    "ReasonSuccess": "Yes, mostly",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "15/03/2022 14:33:30",
    "MainEndSong": "Dietrofront",
    "MainEndSpotifyID": "spotify:track:0pD3ZURkGEUYtFgB8DIgIk",
    "MainEndArtist": "Matteo Vallicelli",
    "MainEndTracktime": "36,091",
    "MoodText": "Very Tired",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Low",
    "ReasonSuccessText": "Mostly"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "15/03/2022 16:37:40",
    "InitStartSong": "Somethinggreater - Single Version",
    "InitStartSpotifyID": "spotify:track:5ec2yrxKI6EhOdYS2XMbUP",
    "InitStartArtist": "Parcels",
    "InitStartTracktime": 16096,
    "InitValence": -3,
    "InitArousal": 1,
    "Mood": "Depressed",
    "InitIntensity": 7,
    "ValenceAim": -1,
    "ArousalAim": -1,
    "MoodAim": 1,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Focused music listening",
    "InitEnd": "15/03/2022 16:37:44",
    "InitEndSong": "Somethinggreater - Single Version",
    "InitEndSpotifyID": "spotify:track:5ec2yrxKI6EhOdYS2XMbUP",
    "InitEndArtist": "Parcels",
    "InitEndTracktime": 20009,
    "MainStart": "15/03/2022 16:43:24",
    "MainStartSong": "anotherlife",
    "MainStartSpotifyID": "spotify:track:4ydCaKmqhbTPCMl7tb8TnR",
    "MainStartArtist": "Nilüfer Yanya",
    "MainStartTracktime": "173,344",
    "MainValence": -3,
    "MainArousal": 1,
    "MainIntensity": 7,
    "MainMusicValence": -3,
    "MainMusicArousal": 1,
    "MusicAttention": 1,
    "Familiar": 1,
    "MainEnjoy": 1,
    "SuitActivity": 1,
    "ReasonMain": "For my mood (Depressed)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel more Depressed",
    "Reason_label": "To feel more <Mood>",
    "ReasonSuccess": "Yes, a little",
    "Strat": "By distracting myself",
    "Strat2": "Shutting off my thoughts",
    "MainEnd": "15/03/2022 16:43:27",
    "MainEndSong": "anotherlife",
    "MainEndSpotifyID": "spotify:track:4ydCaKmqhbTPCMl7tb8TnR",
    "MainEndArtist": "Nilüfer Yanya",
    "MainEndTracktime": "176,468",
    "MoodText": "Extremely Depressed",
    "ValenceText": "Very negative",
    "ArousalText": "Extremely low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 0,
    "ArousalSuccess": 0,
    "SuitableText": "Extremely low",
    "ReasonSuccessText": "Slightly"
  },
  {
    "ValenceChange": 3,
    "ArousalChange": -1,
    "MoodChange": -3,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "16/03/2022 11:05:42",
    "InitStartSong": "Sun Hands",
    "InitStartSpotifyID": "spotify:track:15eWh3ilU9Jdr9rHx4BuaM",
    "InitStartArtist": "Local Natives",
    "InitStartTracktime": 13557,
    "InitValence": -2,
    "InitArousal": 4,
    "Mood": "Angry",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 1,
    "MoodAim": 1,
    "Listeners": "Only me (headphones)",
    "Location": "Travelling / commuting",
    "Activity": "Walking",
    "InitEnd": "16/03/2022 11:05:45",
    "InitEndSong": "Sun Hands",
    "InitEndSpotifyID": "spotify:track:15eWh3ilU9Jdr9rHx4BuaM",
    "InitEndArtist": "Local Natives",
    "InitEndTracktime": 16635,
    "MainStart": "16/03/2022 11:18:15",
    "MainStartSong": "Spend A Lifetime",
    "MainStartSpotifyID": "spotify:track:00L1ptgbOcohvLJXa1Vkel",
    "MainStartArtist": "sir Was",
    "MainStartTracktime": "86,395",
    "MainValence": 1,
    "MainArousal": 3,
    "MainIntensity": 2,
    "MainMusicValence": 1,
    "MainMusicArousal": 2,
    "MusicAttention": 5,
    "Familiar": 6,
    "MainEnjoy": 3,
    "SuitActivity": 6,
    "ReasonMain": "For my mood (Angry)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel more Angry",
    "Reason_label": "To feel more <Mood>",
    "ReasonSuccess": "No, the music was wrong",
    "Strat": "By focussing on my feelings",
    "Strat2": "Seeking comfort in music",
    "MainEnd": "16/03/2022 11:18:24",
    "MainEndSong": "Spend A Lifetime",
    "MainEndSpotifyID": "spotify:track:00L1ptgbOcohvLJXa1Vkel",
    "MainEndArtist": "sir Was",
    "MainEndTracktime": "95,473",
    "MoodText": "Very Angry",
    "ValenceText": "Negative",
    "ArousalText": "Medium energy",
    "MoodSuccess": -1,
    "ValenceSuccess": 0,
    "ArousalSuccess": -1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "No (music)"
  },
  {
    "ValenceChange": 1,
    "ArousalChange": -1,
    "MoodChange": -1,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "16/03/2022 15:18:24",
    "InitStartSong": "Walrus",
    "InitStartSpotifyID": "spotify:track:5Zwymv32Mov1dECDiVYwqi",
    "InitStartArtist": "D.D Dumbo",
    "InitStartTracktime": 10373,
    "InitValence": 0,
    "InitArousal": 4,
    "Mood": "Proud",
    "InitIntensity": 6,
    "ValenceAim": 0,
    "ArousalAim": 0,
    "MoodAim": 0,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Nothing / waiting",
    "InitEnd": "16/03/2022 15:18:27",
    "InitEndSong": "Walrus",
    "InitEndSpotifyID": "spotify:track:5Zwymv32Mov1dECDiVYwqi",
    "InitEndArtist": "D.D Dumbo",
    "InitEndTracktime": 13481,
    "MainStart": "16/03/2022 15:26:34",
    "MainStartSong": "Solitude Is Bliss",
    "MainStartSpotifyID": "spotify:track:7xFqIlAM0uR52zZm7WeC1z",
    "MainStartArtist": "Tame Impala",
    "MainStartTracktime": "80,843",
    "MainValence": 1,
    "MainArousal": 3,
    "MainIntensity": 5,
    "MainMusicValence": -2,
    "MainMusicArousal": 3,
    "MusicAttention": 5,
    "Familiar": 5,
    "MainEnjoy": 3,
    "SuitActivity": 6,
    "ReasonMain": "For entertainment / enjoyment",
    "ReasonMain_label": "Enjoyment",
    "Reason": "For enjoyment / pleasure",
    "Reason_label": "For enjoyment / pleasure",
    "ReasonSuccess": "Yes, completely",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "16/03/2022 15:26:47",
    "MainEndSong": "Solitude Is Bliss",
    "MainEndSpotifyID": "spotify:track:7xFqIlAM0uR52zZm7WeC1z",
    "MainEndArtist": "Tame Impala",
    "MainEndTracktime": "93,202",
    "MoodText": "Very Proud",
    "ValenceText": "Neutral",
    "ArousalText": "Medium energy",
    "MoodSuccess": -1,
    "ValenceSuccess": 1,
    "ArousalSuccess": -1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Completely"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "17/03/2022 09:15:40",
    "InitStartSong": "Steady, As She Goes",
    "InitStartSpotifyID": "spotify:track:4xlEKYv7HmC8zXoJIbpZKM",
    "InitStartArtist": "The Raconteurs",
    "InitStartTracktime": 25658,
    "InitValence": 1,
    "InitArousal": 5,
    "Mood": "Motivated",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 1,
    "MoodAim": 1,
    "Listeners": "Only me (speakers)",
    "Location": "Home",
    "Activity": "Exercising / sports",
    "InitEnd": "17/03/2022 09:15:43",
    "InitEndSong": "Steady, As She Goes",
    "InitEndSpotifyID": "spotify:track:4xlEKYv7HmC8zXoJIbpZKM",
    "InitEndArtist": "The Raconteurs",
    "InitEndTracktime": 253,
    "MainStart": "17/03/2022 09:23:34",
    "MainStartSong": "Go",
    "MainStartSpotifyID": "spotify:track:2GuXIMRlaxVLcU0a5jacHw",
    "MainStartArtist": "The Black Keys",
    "MainStartTracktime": "25,669",
    "MainValence": 1,
    "MainArousal": 5,
    "MainIntensity": 5,
    "MainMusicValence": 1,
    "MainMusicArousal": 6,
    "MusicAttention": 5,
    "Familiar": 2,
    "MainEnjoy": 5,
    "SuitActivity": 6,
    "ReasonMain": "For what I am doing (current activity)",
    "ReasonMain_label": "Activity",
    "Reason": "For enjoyment of what I'm doing",
    "Reason_label": "For enjoyment of <Activity>",
    "ReasonSuccess": "Yes, a little",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "17/03/2022 09:23:38",
    "MainEndSong": "Go",
    "MainEndSpotifyID": "spotify:track:2GuXIMRlaxVLcU0a5jacHw",
    "MainEndArtist": "The Black Keys",
    "MainEndTracktime": "29,132",
    "MoodText": "Very Motivated",
    "ValenceText": "Slightly positive",
    "ArousalText": "High energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 1,
    "ArousalSuccess": 0,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Slightly"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 1,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "17/03/2022 14:09:47",
    "InitStartSong": "Beloved Exile",
    "InitStartSpotifyID": "spotify:track:6GmwkRZj0DlG1j6EDBCwZR",
    "InitStartArtist": "Steve Moore",
    "InitStartTracktime": 13239,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Anxious",
    "InitIntensity": 3,
    "ValenceAim": 0,
    "ArousalAim": 0,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Thinking / problem-solving",
    "InitEnd": "17/03/2022 14:09:49",
    "InitEndSong": "Beloved Exile",
    "InitEndSpotifyID": "spotify:track:6GmwkRZj0DlG1j6EDBCwZR",
    "InitEndArtist": "Steve Moore",
    "InitEndTracktime": 14892,
    "MainStart": "17/03/2022 14:16:35",
    "MainStartSong": "Standing Crosswise in the Square",
    "MainStartSpotifyID": "spotify:track:2ul6NDnL1ID1LFmldqRdhI",
    "MainStartArtist": "Craig Leon",
    "MainStartTracktime": "105,847",
    "MainValence": -1,
    "MainArousal": 3,
    "MainIntensity": 3,
    "MainMusicValence": -1,
    "MainMusicArousal": 2,
    "MusicAttention": 2,
    "Familiar": 1,
    "MainEnjoy": 4,
    "SuitActivity": 6,
    "ReasonMain": "For what I am doing (current activity)",
    "ReasonMain_label": "Activity",
    "Reason": "For background to what I'm doing",
    "Reason_label": "For background to <Activity>",
    "ReasonSuccess": "No, I need more time",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "17/03/2022 14:16:48",
    "MainEndSong": "Standing Crosswise in the Square",
    "MainEndSpotifyID": "spotify:track:2ul6NDnL1ID1LFmldqRdhI",
    "MainEndArtist": "Craig Leon",
    "MainEndTracktime": "12,637",
    "MoodText": "Somewhat Anxious",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "No (time)"
  },
  {
    "ValenceChange": -1,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "17/03/2022 16:45:35",
    "InitStartSong": "Back to Hastings",
    "InitStartSpotifyID": "spotify:track:0Pt4TBaEaUmzU5QW2IE7VN",
    "InitStartArtist": "Alejandro Morse",
    "InitStartTracktime": 16605,
    "InitValence": 0,
    "InitArousal": 2,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 1,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Web browsing",
    "InitEnd": "17/03/2022 16:45:37",
    "InitEndSong": "Back to Hastings",
    "InitEndSpotifyID": "spotify:track:0Pt4TBaEaUmzU5QW2IE7VN",
    "InitEndArtist": "Alejandro Morse",
    "InitEndTracktime": 18315,
    "MainStart": "17/03/2022 17:13:49",
    "MainStartSong": "Glory",
    "MainStartSpotifyID": "spotify:track:77fRc8iT858bzRdcR4k8T8",
    "MainStartArtist": "Snail Mail",
    "MainStartTracktime": "67,624",
    "MainValence": -1,
    "MainArousal": 2,
    "MainIntensity": 5,
    "MainMusicValence": 0,
    "MainMusicArousal": 4,
    "MusicAttention": 3,
    "Familiar": 5,
    "MainEnjoy": 4,
    "SuitActivity": 2,
    "ReasonMain": "For what I am doing (current activity)",
    "ReasonMain_label": "Activity",
    "Reason": "For focus / concentration",
    "Reason_label": "For focus / concentration",
    "ReasonSuccess": "Yes, completely",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "17/03/2022 17:13:55",
    "MainEndSong": "Glory",
    "MainEndSpotifyID": "spotify:track:77fRc8iT858bzRdcR4k8T8",
    "MainEndArtist": "Snail Mail",
    "MainEndTracktime": "73,316",
    "MoodText": "Very Tired",
    "ValenceText": "Neutral",
    "ArousalText": "Very low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": -1,
    "ArousalSuccess": 0,
    "SuitableText": "Very low",
    "ReasonSuccessText": "Completely"
  },
  {
    "ValenceChange": -2,
    "ArousalChange": -1,
    "MoodChange": 2,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "17/03/2022 19:27:00",
    "InitStartSong": "Crushed Velvet",
    "InitStartSpotifyID": "spotify:track:1I0i3wWt1sCZ4PT0TfnyZm",
    "InitStartArtist": "Yves Tumor",
    "InitStartTracktime": 4142,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Upset",
    "InitIntensity": 5,
    "ValenceAim": -1,
    "ArousalAim": -1,
    "MoodAim": 1,
    "Listeners": "Friend(s)",
    "Location": "Someone else’s home",
    "Activity": "Socialising (casual)",
    "InitEnd": "17/03/2022 19:27:03",
    "InitEndSong": "Crushed Velvet",
    "InitEndSpotifyID": "spotify:track:1I0i3wWt1sCZ4PT0TfnyZm",
    "InitEndArtist": "Yves Tumor",
    "InitEndTracktime": 6860,
    "MainStart": "17/03/2022 19:33:12",
    "MainStartSong": "Porta",
    "MainStartSpotifyID": "spotify:track:6zfI5bLVFhDzYUBHmMA7ni",
    "MainStartArtist": "Sharon Van Etten",
    "MainStartTracktime": "16,080",
    "MainValence": -3,
    "MainArousal": 1,
    "MainIntensity": 7,
    "MainMusicValence": -3,
    "MainMusicArousal": 2,
    "MusicAttention": 3,
    "Familiar": 4,
    "MainEnjoy": 5,
    "SuitActivity": 6,
    "ReasonMain": "To relax / calm down",
    "ReasonMain_label": "Relax",
    "Reason": "To calm down",
    "Reason_label": "To calm down",
    "ReasonSuccess": "Yes, mostly",
    "Strat": "By distracting myself",
    "Strat2": "Distracting myself from the situation",
    "MainEnd": "17/03/2022 19:33:15",
    "MainEndSong": "Porta",
    "MainEndSpotifyID": "spotify:track:6zfI5bLVFhDzYUBHmMA7ni",
    "MainEndArtist": "Sharon Van Etten",
    "MainEndTracktime": "18,946",
    "MoodText": "Very Upset",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Mostly"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "20/03/2022 11:41:15",
    "InitStartSong": "Medicine",
    "InitStartSpotifyID": "spotify:track:3jaOfXYnWg49JrTZnrryx4",
    "InitStartArtist": "Broken Bells",
    "InitStartTracktime": 17848,
    "InitValence": 1,
    "InitArousal": 3,
    "Mood": "Curious",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 0,
    "MoodAim": 0,
    "Listeners": "Only me (headphones)",
    "Location": "Home",
    "Activity": "Housework",
    "InitEnd": "20/03/2022 11:41:16",
    "InitEndSong": "Medicine",
    "InitEndSpotifyID": "spotify:track:3jaOfXYnWg49JrTZnrryx4",
    "InitEndArtist": "Broken Bells",
    "InitEndTracktime": 18858,
    "MainStart": "20/03/2022 11:49:56",
    "MainStartSong": "",
    "MainStartSpotifyID": "",
    "MainStartArtist": "",
    "MainStartTracktime": 0,
    "MainValence": 1,
    "MainArousal": 3,
    "MainIntensity": 5,
    "MainMusicValence": -3,
    "MainMusicArousal": 1,
    "MusicAttention": 1,
    "Familiar": 1,
    "MainEnjoy": 1,
    "SuitActivity": 1,
    "ReasonMain": "For entertainment / enjoyment",
    "ReasonMain_label": "Enjoyment",
    "Reason": "To enjoy what I'm doing",
    "Reason_label": "To enjoy <Activity>",
    "ReasonSuccess": "No, I need more time",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "20/03/2022 11:50:03",
    "MainEndSong": "",
    "MainEndSpotifyID": "",
    "MainEndArtist": "",
    "MainEndTracktime": 0,
    "MoodText": "Very Curious",
    "ValenceText": "Slightly positive",
    "ArousalText": "Low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Extremely low",
    "ReasonSuccessText": "No (time)"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 0,
    "MoodChange": "",
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "23/04/2022 15:41:55",
    "InitStartSong": "She's a Rainbow",
    "InitStartSpotifyID": "spotify:track:1XYv25F6qBSjcLk49UN9bE",
    "InitStartArtist": "The Wiggles",
    "InitStartTracktime": 23335,
    "InitValence": 0,
    "InitArousal": 4,
    "Mood": "Neutral",
    "InitIntensity": "",
    "ValenceAim": 0,
    "ArousalAim": 0,
    "MoodAim": 0,
    "Listeners": "Only me (headphones)",
    "Location": "Travelling / commuting",
    "Activity": "On bus / train / plane",
    "InitEnd": "23/04/2022 15:41:56",
    "InitEndSong": "She's a Rainbow",
    "InitEndSpotifyID": "spotify:track:1XYv25F6qBSjcLk49UN9bE",
    "InitEndArtist": "The Wiggles",
    "InitEndTracktime": 25014,
    "MainStart": "23/04/2022 15:49:01",
    "MainStartSong": "Sunday Girl",
    "MainStartSpotifyID": "spotify:track:16FnHkvAZzYK0IJTDo8Ub2",
    "MainStartArtist": "The Wiggles",
    "MainStartTracktime": "80,167",
    "MainValence": 0,
    "MainArousal": 4,
    "MainIntensity": "",
    "MainMusicValence": -3,
    "MainMusicArousal": 2,
    "MusicAttention": 3,
    "Familiar": 4,
    "MainEnjoy": 5,
    "SuitActivity": 6,
    "ReasonMain": "For boredom / habit",
    "ReasonMain_label": "Boredom",
    "Reason": "To pass the time",
    "Reason_label": "To pass the time",
    "ReasonSuccess": "Yes, mostly",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "23/04/2022 15:49:04",
    "MainEndSong": "Sunday Girl",
    "MainEndSpotifyID": "spotify:track:16FnHkvAZzYK0IJTDo8Ub2",
    "MainEndArtist": "The Wiggles",
    "MainEndTracktime": "83,148",
    "MoodText": "Neutral",
    "ValenceText": "Neutral",
    "ArousalText": "Medium energy",
    "MoodSuccess": "",
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Mostly"
  },
  {
    "ValenceChange": 1,
    "ArousalChange": 2,
    "MoodChange": -1,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "03/05/2022 14:55:10",
    "InitStartSong": "People, I've been sad",
    "InitStartSpotifyID": "spotify:track:0KywIrJ4Xir4tS6q61aY1W",
    "InitStartArtist": "Christine and the Queens",
    "InitStartTracktime": 21517,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 1,
    "ArousalAim": 0,
    "MoodAim": 0,
    "Listeners": "Only me (speakers)",
    "Location": "Someone else’s home",
    "Activity": "Housework",
    "InitEnd": "03/05/2022 14:55:12",
    "InitEndSong": "People, I've been sad",
    "InitEndSpotifyID": "spotify:track:0KywIrJ4Xir4tS6q61aY1W",
    "InitEndArtist": "Christine and the Queens",
    "InitEndTracktime": 24093,
    "MainStart": "03/05/2022 15:01:59",
    "MainStartSong": "Like in the Movies",
    "MainStartSpotifyID": "spotify:track:3GXeJYfUcnvdmMMyyiQqCH",
    "MainStartArtist": "Vlad Holiday",
    "MainStartTracktime": "12,744",
    "MainValence": 0,
    "MainArousal": 4,
    "MainIntensity": 4,
    "MainMusicValence": -3,
    "MainMusicArousal": 2,
    "MusicAttention": 3,
    "Familiar": 4,
    "MainEnjoy": 5,
    "SuitActivity": 6,
    "ReasonMain": "For thinking / reflecting",
    "ReasonMain_label": "Thinking",
    "Reason": "To clear my mind",
    "Reason_label": "To clear my mind",
    "ReasonSuccess": "Yes, a little",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "03/05/2022 15:02:02",
    "MainEndSong": "Like in the Movies",
    "MainEndSpotifyID": "spotify:track:3GXeJYfUcnvdmMMyyiQqCH",
    "MainEndArtist": "Vlad Holiday",
    "MainEndTracktime": "15,658",
    "MoodText": "Very Tired",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": -1,
    "ValenceSuccess": 1,
    "ArousalSuccess": 0,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Slightly"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "04/05/2022 13:57:40",
    "InitStartSong": "Lemon Glow",
    "InitStartSpotifyID": "spotify:track:5Jqbh9wk9H74RmFjobgBTZ",
    "InitStartArtist": "Beach House",
    "InitStartTracktime": 1233,
    "InitValence": 0,
    "InitArousal": 3,
    "Mood": "Motivated",
    "InitIntensity": 4,
    "ValenceAim": 1,
    "ArousalAim": 0,
    "MoodAim": 0,
    "Listeners": "Only me (headphones)",
    "Location": "Other (outside)",
    "Activity": "Walking",
    "InitEnd": "04/05/2022 13:57:47",
    "InitEndSong": "Lemon Glow",
    "InitEndSpotifyID": "spotify:track:5Jqbh9wk9H74RmFjobgBTZ",
    "InitEndArtist": "Beach House",
    "InitEndTracktime": 8576,
    "MainStart": "04/05/2022 14:11:07",
    "MainStartSong": "Gooey",
    "MainStartSpotifyID": "spotify:track:1rvwsCXRTiERpyTwzDBawG",
    "MainStartArtist": "Glass Animals",
    "MainStartTracktime": "80,264",
    "MainValence": 0,
    "MainArousal": 3,
    "MainIntensity": 4,
    "MainMusicValence": -1,
    "MainMusicArousal": 3,
    "MusicAttention": 5,
    "Familiar": 7,
    "MainEnjoy": 6,
    "SuitActivity": 6,
    "ReasonMain": "For thinking / reflecting",
    "ReasonMain_label": "Thinking",
    "Reason": "For motivation",
    "Reason_label": "For motivation",
    "ReasonSuccess": "No, the music was wrong",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "04/05/2022 14:11:10",
    "MainEndSong": "Gooey",
    "MainEndSpotifyID": "spotify:track:1rvwsCXRTiERpyTwzDBawG",
    "MainEndArtist": "Glass Animals",
    "MainEndTracktime": "83,215",
    "MoodText": "Somewhat Motivated",
    "ValenceText": "Neutral",
    "ArousalText": "Low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 0,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "No (music)"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 1,
    "MoodChange": -1,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "05/05/2022 16:21:28",
    "InitStartSong": "Where's My Brain???",
    "InitStartSpotifyID": "spotify:track:5pBldI3YMOL2zzdikNd2wR",
    "InitStartArtist": "The Lazy Eyes",
    "InitStartTracktime": 16787,
    "InitValence": 0,
    "InitArousal": 3,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 1,
    "ArousalAim": 1,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Someone else’s home",
    "Activity": "Web browsing",
    "InitEnd": "05/05/2022 16:21:30",
    "InitEndSong": "Where's My Brain???",
    "InitEndSpotifyID": "spotify:track:5pBldI3YMOL2zzdikNd2wR",
    "InitEndArtist": "The Lazy Eyes",
    "InitEndTracktime": 18430,
    "MainStart": "05/05/2022 16:27:34",
    "MainStartSong": "Cheesy Love Song - Edit",
    "MainStartSpotifyID": "spotify:track:7eJfFLLf3DRiSJPFPvHwzm",
    "MainStartArtist": "The Lazy Eyes",
    "MainStartTracktime": "93,046",
    "MainValence": 0,
    "MainArousal": 4,
    "MainIntensity": 4,
    "MainMusicValence": -1,
    "MainMusicArousal": 3,
    "MusicAttention": 4,
    "Familiar": 1,
    "MainEnjoy": 5,
    "SuitActivity": 6,
    "ReasonMain": "To focus on the music",
    "ReasonMain_label": "MusicFocus",
    "Reason": "To prepare for a festival / concert",
    "Reason_label": "To prepare for a festival / concert",
    "ReasonSuccess": "Yes, completely",
    "Strat": "",
    "Strat2": "",
    "MainEnd": "05/05/2022 16:27:38",
    "MainEndSong": "Cheesy Love Song - Edit",
    "MainEndSpotifyID": "spotify:track:7eJfFLLf3DRiSJPFPvHwzm",
    "MainEndArtist": "The Lazy Eyes",
    "MainEndTracktime": "96,832",
    "MoodText": "Very Tired",
    "ValenceText": "Neutral",
    "ArousalText": "Low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 0,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Completely"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 3,
    "MoodChange": -2,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "01/09/2022 14:36:14",
    "InitStartSong": "Narcose",
    "InitStartSpotifyID": "spotify:track:5rLMfM9jN1i6GyE83f2L8D",
    "InitStartArtist": "Meteor",
    "InitStartTracktime": 24948,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 1,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Thinking / problem-solving",
    "InitEnd": "01/09/2022 14:36:17",
    "InitEndSong": "Narcose",
    "InitEndSpotifyID": "spotify:track:5rLMfM9jN1i6GyE83f2L8D",
    "InitEndArtist": "Meteor",
    "InitEndTracktime": 27898,
    "MainStart": "01/09/2022 14:42:53",
    "MainStartSong": "Whistleman",
    "MainStartSpotifyID": "spotify:track:386PnZfbszq42M8GprZnVt",
    "MainStartArtist": "Bedouin",
    "MainStartTracktime": "283,174",
    "MainValence": -1,
    "MainArousal": 5,
    "MainIntensity": 3,
    "MainMusicValence": -2,
    "MainMusicArousal": 5,
    "MusicAttention": 3,
    "Familiar": 5,
    "MainEnjoy": 2,
    "SuitActivity": 6,
    "ReasonMain": "To raise / boost energy",
    "ReasonMain_label": "RaiseEnergy",
    "Reason": "To raise / boost energy",
    "Reason_label": "To raise / boost energy",
    "ReasonSuccess": "Yes, a little",
    "Strat": "By distracting myself",
    "Strat2": "Distracting myself from the situation",
    "MainEnd": "01/09/2022 14:43:04",
    "MainEndSong": "Whistleman",
    "MainEndSpotifyID": "spotify:track:386PnZfbszq42M8GprZnVt",
    "MainEndArtist": "Bedouin",
    "MainEndTracktime": "294,132",
    "MoodText": "Very Tired",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Slightly"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": -1,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "01/09/2022 16:32:01",
    "InitStartSong": "A Brief Walk in the Sea",
    "InitStartSpotifyID": "spotify:track:1O3wMxzAagYQ336rdfH9bQ",
    "InitStartArtist": "Near The Parenthesis",
    "InitStartTracktime": 10528,
    "InitValence": 1,
    "InitArousal": 3,
    "Mood": "Hopeful",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 0,
    "MoodAim": 1,
    "Listeners": "Only me (headphones)",
    "Location": "Restaurant / cafe",
    "Activity": "Gaming / entertainment",
    "InitEnd": "01/09/2022 16:32:02",
    "InitEndSong": "A Brief Walk in the Sea",
    "InitEndSpotifyID": "spotify:track:1O3wMxzAagYQ336rdfH9bQ",
    "InitEndArtist": "Near The Parenthesis",
    "InitEndTracktime": 11366,
    "MainStart": "01/09/2022 16:37:56",
    "MainStartSong": "A Brief Walk in the Sea",
    "MainStartSpotifyID": "spotify:track:1O3wMxzAagYQ336rdfH9bQ",
    "MainStartArtist": "Near The Parenthesis",
    "MainStartTracktime": "365,584",
    "MainValence": 1,
    "MainArousal": 2,
    "MainIntensity": 5,
    "MainMusicValence": 2,
    "MainMusicArousal": 2,
    "MusicAttention": 5,
    "Familiar": 6,
    "MainEnjoy": 2,
    "SuitActivity": 6,
    "ReasonMain": "For my mood (Hopeful)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel more Hopeful",
    "Reason_label": "To feel more <Mood>",
    "ReasonSuccess": "No, I need more time",
    "Strat": "By focussing on my body",
    "Strat2": "Meditating",
    "MainEnd": "01/09/2022 16:37:59",
    "MainEndSong": "A Brief Walk in the Sea",
    "MainEndSpotifyID": "spotify:track:1O3wMxzAagYQ336rdfH9bQ",
    "MainEndArtist": "Near The Parenthesis",
    "MainEndTracktime": "368,581",
    "MoodText": "Very Hopeful",
    "ValenceText": "Slightly positive",
    "ArousalText": "Low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 1,
    "ArousalSuccess": -1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "No (time)"
  },
  {
    "ValenceChange": 2,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "01/09/2022 22:14:56",
    "InitStartSong": "Your Light",
    "InitStartSpotifyID": "spotify:track:6vYRwtuNmaQJg7SlcrMdPs",
    "InitStartArtist": "The Big Moon",
    "InitStartTracktime": 27734,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 1,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Home",
    "Activity": "Focused music listening",
    "InitEnd": "01/09/2022 22:14:59",
    "InitEndSong": "Your Light",
    "InitEndSpotifyID": "spotify:track:6vYRwtuNmaQJg7SlcrMdPs",
    "InitEndArtist": "The Big Moon",
    "InitEndTracktime": 29867,
    "MainStart": "01/09/2022 22:21:37",
    "MainStartSong": "Your Light",
    "MainStartSpotifyID": "spotify:track:6vYRwtuNmaQJg7SlcrMdPs",
    "MainStartArtist": "The Big Moon",
    "MainStartTracktime": "129,291",
    "MainValence": 1,
    "MainArousal": 2,
    "MainIntensity": 5,
    "MainMusicValence": 1,
    "MainMusicArousal": 6,
    "MusicAttention": 5,
    "Familiar": 6,
    "MainEnjoy": 6,
    "SuitActivity": 6,
    "ReasonMain": "For my mood (Tired)",
    "ReasonMain_label": "Mood",
    "Reason": "To create a different mood",
    "Reason_label": "To cope with a situation",
    "ReasonSuccess": "Yes, completely",
    "Strat": "By focussing on my body",
    "Strat2": "Meditating",
    "MainEnd": "01/09/2022 22:21:42",
    "MainEndSong": "Your Light",
    "MainEndSpotifyID": "spotify:track:6vYRwtuNmaQJg7SlcrMdPs",
    "MainEndArtist": "The Big Moon",
    "MainEndTracktime": "133,993",
    "MoodText": "Very Tired",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 0,
    "ArousalSuccess": 0,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Completely"
  },
  {
    "ValenceChange": -1,
    "ArousalChange": 1,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "02/09/2022 11:48:55",
    "InitStartSong": "Piany Pianino",
    "InitStartSpotifyID": "spotify:track:6ZrauffaDWD1kaN4Z6pFVh",
    "InitStartArtist": "Thylacine",
    "InitStartTracktime": 31815,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Lonely",
    "InitIntensity": 5,
    "ValenceAim": 1,
    "ArousalAim": 1,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Work",
    "Activity": "Nothing / waiting",
    "InitEnd": "02/09/2022 11:49:01",
    "InitEndSong": "Piany Pianino",
    "InitEndSpotifyID": "spotify:track:6ZrauffaDWD1kaN4Z6pFVh",
    "InitEndArtist": "Thylacine",
    "InitEndTracktime": 37542,
    "MainStart": "02/09/2022 11:55:03",
    "MainStartSong": "Soopertrack",
    "MainStartSpotifyID": "spotify:track:0tZFL2LU8XSThRttMJif6Q",
    "MainStartArtist": "Extrawelt",
    "MainStartTracktime": "126,906",
    "MainValence": -2,
    "MainArousal": 3,
    "MainIntensity": 5,
    "MainMusicValence": -1,
    "MainMusicArousal": 5,
    "MusicAttention": 3,
    "Familiar": 6,
    "MainEnjoy": 6,
    "SuitActivity": 6,
    "ReasonMain": "For my mood (Lonely)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel less Lonely",
    "Reason_label": "To feel less <Mood>",
    "ReasonSuccess": "Yes, mostly",
    "Strat": "By focussing on my thoughts",
    "Strat2": "Going over the details repeatedly",
    "MainEnd": "02/09/2022 11:55:07",
    "MainEndSong": "Soopertrack",
    "MainEndSpotifyID": "spotify:track:0tZFL2LU8XSThRttMJif6Q",
    "MainEndArtist": "Extrawelt",
    "MainEndTracktime": "130,810",
    "MoodText": "Very Lonely",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": -1,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Mostly"
  },
  {
    "ValenceChange": 5,
    "ArousalChange": 1,
    "MoodChange": -2,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "02/09/2022 16:46:03",
    "InitStartSong": "We're Not In Orbit Yet…",
    "InitStartSpotifyID": "spotify:track:45iaKryj5SvdzinlHHrDlL",
    "InitStartArtist": "Broken Bells",
    "InitStartTracktime": 12333,
    "InitValence": -3,
    "InitArousal": 1,
    "Mood": "Depressed",
    "InitIntensity": 7,
    "ValenceAim": -1,
    "ArousalAim": -1,
    "MoodAim": 1,
    "Listeners": "Only me (speakers)",
    "Location": "Travelling / commuting",
    "Activity": "In a car (road trip)",
    "InitEnd": "02/09/2022 16:46:04",
    "InitEndSong": "We're Not In Orbit Yet…",
    "InitEndSpotifyID": "spotify:track:45iaKryj5SvdzinlHHrDlL",
    "InitEndArtist": "Broken Bells",
    "InitEndTracktime": 13097,
    "MainStart": "02/09/2022 17:02:42",
    "MainStartSong": "I Saw You Close Your Eyes",
    "MainStartSpotifyID": "spotify:track:5AKYyNPYhumqKeOMhdEgQO",
    "MainStartArtist": "Local Natives",
    "MainStartTracktime": "45,425",
    "MainValence": 2,
    "MainArousal": 2,
    "MainIntensity": 5,
    "MainMusicValence": 1,
    "MainMusicArousal": 2,
    "MusicAttention": 6,
    "Familiar": 2,
    "MainEnjoy": 6,
    "SuitActivity": 2,
    "ReasonMain": "For my mood (Depressed)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel more Depressed",
    "Reason_label": "To feel more <Mood>",
    "ReasonSuccess": "No, I need more time",
    "Strat": "By focussing on my feelings",
    "Strat2": "Feeling intensely what the music expresses",
    "MainEnd": "02/09/2022 17:02:44",
    "MainEndSong": "I Saw You Close Your Eyes",
    "MainEndSpotifyID": "spotify:track:5AKYyNPYhumqKeOMhdEgQO",
    "MainEndArtist": "Local Natives",
    "MainEndTracktime": "47,567",
    "MoodText": "Extremely Depressed",
    "ValenceText": "Very negative",
    "ArousalText": "Extremely low energy",
    "MoodSuccess": -1,
    "ValenceSuccess": -1,
    "ArousalSuccess": -1,
    "SuitableText": "Very low",
    "ReasonSuccessText": "No (time)"
  },
  {
    "ValenceChange": 4,
    "ArousalChange": 2,
    "MoodChange": 1,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "04/09/2022 00:56:03",
    "InitStartSong": "Inside Out",
    "InitStartSpotifyID": "spotify:track:7qCZgvV98j6RjUULW1s1it",
    "InitStartArtist": "Spoon",
    "InitStartTracktime": 22604,
    "InitValence": -2,
    "InitArousal": 1,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 0,
    "MoodAim": 1,
    "Listeners": "Only me (speakers)",
    "Location": "Travelling / commuting",
    "Activity": "In a car (road trip)",
    "InitEnd": "04/09/2022 00:56:04",
    "InitEndSong": "Inside Out",
    "InitEndSpotifyID": "spotify:track:7qCZgvV98j6RjUULW1s1it",
    "InitEndArtist": "Spoon",
    "InitEndTracktime": 23824,
    "MainStart": "04/09/2022 01:01:42",
    "MainStartSong": "Australia",
    "MainStartSpotifyID": "spotify:track:47TQjzeG4KI0XWWb0wkbri",
    "MainStartArtist": "The Shins",
    "MainStartTracktime": "26,105",
    "MainValence": 2,
    "MainArousal": 3,
    "MainIntensity": 6,
    "MainMusicValence": -2,
    "MainMusicArousal": 5,
    "MusicAttention": 3,
    "Familiar": 6,
    "MainEnjoy": 2,
    "SuitActivity": 6,
    "ReasonMain": "For my mood (Tired)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel more Tired",
    "Reason_label": "To feel more <Mood>",
    "ReasonSuccess": "Yes, mostly",
    "Strat": "By distracting myself",
    "Strat2": "Distracting myself from the situation",
    "MainEnd": "04/09/2022 01:01:44",
    "MainEndSong": "Australia",
    "MainEndSpotifyID": "spotify:track:47TQjzeG4KI0XWWb0wkbri",
    "MainEndArtist": "The Shins",
    "MainEndTracktime": "27,605",
    "MoodText": "Very Tired",
    "ValenceText": "Negative",
    "ArousalText": "Extremely low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 0,
    "ArousalSuccess": 0,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Mostly"
  },
  {
    "ValenceChange": 0,
    "ArousalChange": 0,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "04/09/2022 14:01:30",
    "InitStartSong": "Black Hills",
    "InitStartSpotifyID": "spotify:track:0yGPurznh6Yvwm4uLzSGuB",
    "InitStartArtist": "Gardens & Villa",
    "InitStartTracktime": 17187,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Tired",
    "InitIntensity": 5,
    "ValenceAim": 1,
    "ArousalAim": 0,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Shops / market",
    "Activity": "Shopping",
    "InitEnd": "04/09/2022 14:01:31",
    "InitEndSong": "Black Hills",
    "InitEndSpotifyID": "spotify:track:0yGPurznh6Yvwm4uLzSGuB",
    "InitEndArtist": "Gardens & Villa",
    "InitEndTracktime": 18256,
    "MainStart": "04/09/2022 14:16:05",
    "MainStartSong": "End of The Empire I-III",
    "MainStartSpotifyID": "spotify:track:5VHRFAqgPpC14U10Zdfk2r",
    "MainStartArtist": "Arcade Fire",
    "MainStartTracktime": "33,530",
    "MainValence": -1,
    "MainArousal": 2,
    "MainIntensity": 5,
    "MainMusicValence": -2,
    "MainMusicArousal": 6,
    "MusicAttention": 3,
    "Familiar": 5,
    "MainEnjoy": 6,
    "SuitActivity": 2,
    "ReasonMain": "For my mood (Tired)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel less Tired",
    "Reason_label": "To feel less <Mood>",
    "ReasonSuccess": "Yes, a little",
    "Strat": "By distracting myself",
    "Strat2": "Shutting off my thoughts",
    "MainEnd": "04/09/2022 14:16:08",
    "MainEndSong": "End of The Empire I-III",
    "MainEndSpotifyID": "spotify:track:5VHRFAqgPpC14U10Zdfk2r",
    "MainEndArtist": "Arcade Fire",
    "MainEndTracktime": "36,504",
    "MoodText": "Very Tired",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 0,
    "ValenceSuccess": 0,
    "ArousalSuccess": 1,
    "SuitableText": "Very low",
    "ReasonSuccessText": "Slightly"
  },
  {
    "ValenceChange": 1,
    "ArousalChange": -1,
    "MoodChange": 0,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "05/09/2022 09:28:05",
    "InitStartSong": "#289 — Time Management for Mortals",
    "InitStartSpotifyID": "spotify:episode:3FnxAIhYA7pKHvRhhwMT1p",
    "InitStartArtist": "",
    "InitStartTracktime": 6127,
    "InitValence": 0,
    "InitArousal": 3,
    "Mood": "Motivated",
    "InitIntensity": 5,
    "ValenceAim": 0,
    "ArousalAim": 1,
    "MoodAim": 0,
    "Listeners": "Only me (headphones)",
    "Location": "School / university",
    "Activity": "Exercising / sports",
    "InitEnd": "05/09/2022 09:28:08",
    "InitEndSong": "#289 — Time Management for Mortals",
    "InitEndSpotifyID": "spotify:episode:3FnxAIhYA7pKHvRhhwMT1p",
    "InitEndArtist": "",
    "InitEndTracktime": 8911,
    "MainStart": "05/09/2022 09:41:07",
    "MainStartSong": "#289 — Time Management for Mortals",
    "MainStartSpotifyID": "spotify:episode:3FnxAIhYA7pKHvRhhwMT1p",
    "MainStartArtist": "",
    "MainStartTracktime": "36,610",
    "MainValence": 1,
    "MainArousal": 2,
    "MainIntensity": 5,
    "MainMusicValence": -1,
    "MainMusicArousal": 6,
    "MusicAttention": 2,
    "Familiar": 5,
    "MainEnjoy": 6,
    "SuitActivity": 3,
    "ReasonMain": "For my mood (Motivated)",
    "ReasonMain_label": "Mood",
    "Reason": "To maintain Motivated mood",
    "Reason_label": "To maintain <Mood> mood",
    "ReasonSuccess": "No, the music was wrong",
    "Strat": "By focussing on my body",
    "Strat2": "Feeling intensely what the music expresses",
    "MainEnd": "05/09/2022 09:41:09",
    "MainEndSong": "#289 — Time Management for Mortals",
    "MainEndSpotifyID": "spotify:episode:3FnxAIhYA7pKHvRhhwMT1p",
    "MainEndArtist": "",
    "MainEndTracktime": "38,277",
    "MoodText": "Very Motivated",
    "ValenceText": "Neutral",
    "ArousalText": "Low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 1,
    "ArousalSuccess": -1,
    "SuitableText": "Low",
    "ReasonSuccessText": "No (music)"
  },
  {
    "ValenceChange": 2,
    "ArousalChange": 0,
    "MoodChange": -3,
    "ID": 2729,
    "StudyID": 99,
    "InitStart": "07/09/2022 15:52:15",
    "InitStartSong": "Daphine",
    "InitStartSpotifyID": "spotify:track:0XwJ2kXGE6glUGOg7BrCPB",
    "InitStartArtist": "Algy Lacey",
    "InitStartTracktime": 12247,
    "InitValence": -1,
    "InitArousal": 2,
    "Mood": "Anxious",
    "InitIntensity": 6,
    "ValenceAim": 1,
    "ArousalAim": 0,
    "MoodAim": -1,
    "Listeners": "Only me (headphones)",
    "Location": "Home",
    "Activity": "Focused music listening",
    "InitEnd": "07/09/2022 15:52:16",
    "InitEndSong": "Daphine",
    "InitEndSpotifyID": "spotify:track:0XwJ2kXGE6glUGOg7BrCPB",
    "InitEndArtist": "Algy Lacey",
    "InitEndTracktime": 13332,
    "MainStart": "07/09/2022 15:59:12",
    "MainStartSong": "Waves are coming",
    "MainStartSpotifyID": "spotify:track:4m6jCOTDZfNhKA7qUEpo98",
    "MainStartArtist": "Nicole Rosario",
    "MainStartTracktime": "67,948",
    "MainValence": 1,
    "MainArousal": 2,
    "MainIntensity": 3,
    "MainMusicValence": 1,
    "MainMusicArousal": 2,
    "MusicAttention": 5,
    "Familiar": 3,
    "MainEnjoy": 5,
    "SuitActivity": 6,
    "ReasonMain": "For my mood (Anxious)",
    "ReasonMain_label": "Mood",
    "Reason": "To feel less Anxious",
    "Reason_label": "To feel less <Mood>",
    "ReasonSuccess": "Yes, completely",
    "Strat": "By focussing on my feelings",
    "Strat2": "Seeking comfort in music",
    "MainEnd": "07/09/2022 15:59:17",
    "MainEndSong": "Waves are coming",
    "MainEndSpotifyID": "spotify:track:4m6jCOTDZfNhKA7qUEpo98",
    "MainEndArtist": "Nicole Rosario",
    "MainEndTracktime": "73,551",
    "MoodText": "Very Anxious",
    "ValenceText": "Slightly negative",
    "ArousalText": "Very low energy",
    "MoodSuccess": 1,
    "ValenceSuccess": 1,
    "ArousalSuccess": 1,
    "SuitableText": "Very high",
    "ReasonSuccessText": "Completely"
  }
]
